### ISSUE TITLE
String vs boolean comparison with open links file

### ISSUE THREAD

**Issue by Acidham** [Stephen-Lon/Alfred-workflow-save-ur-url#2]
The latest version v2.1 is not evaluating conditionals in the right way. `links` result in an error instead of opening the file.

It is related to this conditional. You should use `is true` condition instead of `is equal` string comparison.

<img width="1163" alt="Screenshot 2023-08-10 at 08 09 51" src="https://github.com/Stephen-Lon/Alfred-workflow-save-ur-url/assets/17712121/325a8128-0b00-4321-bc6e-7db1bec1ab24">

**Comment by Stephen-Lon** [comment]
I'm so sorry: I knew the correct form of the conditional but was careless and then copied the carelessness! Thanks for pointing it out. V 2.2 will be up any moment…
