### ISSUE TITLE
FR: Ability to revert to the last clipboard entry

### ISSUE THREAD

**Issue by spiritualgeek** [Stephen-Lon/Alfred-workflow-save-ur-url#5]
Hi,

I've been using this for a while and it's very useful. Thanks!

Some sites do not offer up the page title, meaning that you would often copy something from the page to act as the title, but as soon as you invoke the action you cannot retrieve what you copied. Would it be possible to explore a way around this?

Thanks

**Comment by Stephen-Lon** [comment]
Thanks for the kind comment.

I'm afraid what you mention is a consequence of the way in which Alfred currently works. (You can see that by clicking anywhere else if you have an Alfred window open: you will immediately lose the Alfred window.) I'm not aware at present of a simple work-around. I suppose it would be possible to provide for some intermediate save and retrieval but I'm not inclined to delve into those complexities when the easier solution (of typing in a title) is available.

I don't mean to belittle your request at all but you are the only person who has mentioned this so I suspect that people are using the current solution where no page title is available.

**Comment by spiritualgeek** [comment]
The medium.com site is one offender, but there are others as well

I just flick to VSCode presently to manually update, but it breaks the workflow

Thanks

**Comment by spiritualgeek** [comment]
Hi @Stephen-Lon 

Made my own adaptation

<img width="680" alt="image" src="https://github.com/Stephen-Lon/Alfred-workflow-save-ur-url/assets/53917562/f45018a0-24d9-41c3-90d6-e4936722c2ba">

Thanks

**Comment by Stephen-Lon** [comment]
I'm happy if that works for you in practice.

**Comment by spiritualgeek** [comment]
I am not sure how many have downloaded the workflow, but I've been bumping into many sites giving issues and it was bugging me 😄 

Just posted it in case it helps anyone else that might be scratching their head

The check is simple, in case anyone sees this:

<img width="883" alt="image" src="https://github.com/Stephen-Lon/Alfred-workflow-save-ur-url/assets/53917562/4f2b4547-e4c2-4489-b8cf-633a531c6cc8">

Take care
